import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { ListToolsRequestSchema, CallToolRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import fs from "fs";
import path from "path";

const server = new Server({
  name: "daily-digest-mcp",
  version: "1.0.0",
}, {
  capabilities: {
    tools: {},
  }
});

const contentDir = path.join(process.cwd(), "content", "digests");

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "get_latest_digest",
        description: "Read the most recent Daily Digest generated by the AI pipeline.",
        inputSchema: { type: "object", properties: {} }
      },
      {
        name: "search_digests",
        description: "Search all past tech daily digests for a specific keyword, model, or topic.",
        inputSchema: {
          type: "object",
          properties: {
            query: { type: "string", description: "The term or topic to search for" }
          },
          required: ["query"]
        }
      }
    ]
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === "get_latest_digest") {
    if (!fs.existsSync(contentDir)) return { content: [{ type: "text", text: "No digests found in the archive." }] };
    const files = fs.readdirSync(contentDir).filter(f => f.endsWith('.md')).sort().reverse();
    if (files.length === 0) return { content: [{ type: "text", text: "No digests found in the archive." }] };
    
    const latest = fs.readFileSync(path.join(contentDir, files[0]), 'utf-8');
    return { content: [{ type: "text", text: `Digest from ${files[0].replace('.md', '')}:\n\n${latest}` }] };
  }
  
  if (request.params.name === "search_digests") {
    const query = String(request.params.arguments?.query || "").toLowerCase();
    if (!fs.existsSync(contentDir)) return { content: [{ type: "text", text: "No digests found in the archive." }] };
    const files = fs.readdirSync(contentDir).filter(f => f.endsWith('.md')).sort().reverse();
    
    let results = [];
    for (const file of files) {
      const content = fs.readFileSync(path.join(contentDir, file), 'utf-8');
      if (content.toLowerCase().includes(query)) {
        results.push(`--- MATCH IN ${file} ---\n${content.substring(0, 2000)}...\n`);
      }
    }
    
    return { content: [{ type: "text", text: results.length > 0 ? results.join('\n') : "No matches found." }] };
  }

  throw new Error("Tool not found");
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Daily Digest MCP Server running on stdio");
}

main().catch(console.error);
